### ISSUE TITLE
Error on map vertical profile

### ISSUE THREAD

**Issue by lz1asl** [lz1asl/CaveSurvey#45]
See Bankovica map to reproduce

**Comment by lz1asl** [comment]
java.lang.NullPointerException
 	at com.astoev.cave.survey.activity.map.MapUtilities.addDegrees(MapUtilities.java:116)
 	at com.astoev.cave.survey.activity.map.MapUtilities.add90Degrees(MapUtilities.java:112)
 	at com.astoev.cave.survey.activity.map.MapView.onDraw(MapView.java:316)
