### ISSUE TITLE
Crash on Vector create

### ISSUE THREAD

**Issue by jivkoto** [lz1asl/CaveSurvey#70]
App crashes on attempt to add vector.
Steps to reproduce:
1. Open point
2. Choose add vector option
3. start entering the values
4. Rotate the screen on 90degrees
5. Hit save
Exception occurs

10-12 23:38:04.403    7285-7285/com.astoev.cave.survey D/CaveSurveyUI﹕ Creating main menu
10-12 23:38:04.407    7285-7285/com.astoev.cave.survey I/CaveSurveySVC﹕ Search last leg for project 1
10-12 23:38:05.452    7285-7285/com.astoev.cave.survey D/AndroidRuntime﹕ Shutting down VM
10-12 23:38:05.453    7285-7285/com.astoev.cave.survey E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.astoev.cave.survey, PID: 7285
    java.lang.NullPointerException: Attempt to invoke virtual method 'com.astoev.cave.survey.model.Point com.astoev.cave.survey.model.Leg.getFromPoint()' on a null object reference
            at com.astoev.cave.survey.activity.dialog.VectorDialog$1.onClick(VectorDialog.java:103)
            at android.view.View.performClick(View.java:4780)
            at android.view.View$PerformClick.run(View.java:19866)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
10-12 23:38:25.784    7285-7285/com.astoev.cave.survey I/Process﹕ Sending signal. PID: 7285 SIG: 9
10-12 23:38:26.063    8104-8104/com.astoev.cave.survey I/CaveSurveyUI﹕ Creating activity com.astoev.cave.survey.activity.main.MainActivity
10-12 23:38:26.156    8104-8104/com.astoev.cave.survey V/CaveSurveySVC﹕ Initialize workspace

**Comment by jivkoto** [comment]
Fiexed
