### ISSUE TITLE
bug drawing the vertical profile

### ISSUE THREAD

**Issue by lz1asl** [lz1asl/CaveSurvey#99]
see "rakitovo" test survey

**Comment by lz1asl** [comment]
`05-28 16:18:00.139: E/CaveSurveyUI(1943): java.lang.NullPointerException
05-28 16:18:00.139: E/CaveSurveyUI(1943): 	at com.astoev.cave.survey.activity.map.MapView.calculateAndDrawSide(MapView.java:451)
05-28 16:18:00.139: E/CaveSurveyUI(1943): 	at com.astoev.cave.survey.activity.map.MapView.onDraw(MapView.java:307)
`
